# Generated by Django 2.2.19 on 2022-05-22 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20220522_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='titel',
            field=models.CharField(max_length=100),
        ),
    ]
