# Generated by Django 2.2.19 on 2022-05-22 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20220522_1424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='titel',
            new_name='title',
        ),
    ]
